# NumPy Python Package

NumPy stands for Numeric Python. NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [ ]:
!pip install numpy

In [1]:
import numpy as np

### Creating a NumPy array

In [2]:
lst = [7,2,3]

In [3]:
np.array(lst)

array([7, 2, 3])

In [4]:
type(np.array(lst))

numpy.ndarray

In [8]:
arr = np.array(lst)

In [9]:
arr

array([1, 2, 3])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Multiple numpy.ndarrays vertically

In [7]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### Methods available in NumPy arrays

In [9]:
arr=np.array([122,3,4,55,98,67])

In [10]:
arr.max()

122

In [11]:
arr.sum()

349

In [18]:
arr.min()

3

In [12]:
arr.mean()

58.166666666666664

In [13]:
arr.argmax()

0

In [14]:
arr.argmin()

1

In [26]:
print(arr)
print(arr.shape)

[122   3   4  55  98  67]
(6,)


### Reshaping the array, Shape - rows and colums

In [28]:
arr = arr.reshape(2,3)
print(arr)
arr.shape

[[122   3   4]
 [ 55  98  67]]


(2, 3)

## The numpy arange() function
It is similar to range function in fuction

In [25]:
mat=np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
#mat.reshape(10,10)

### Indexing and Slicing in NumPy array

In [27]:
mat[0,1]

1

In [33]:
mat[4,3]

43

In [34]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [36]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [37]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
a = np.array([1.5, 2])
print(a)

[1.5 2. ]


## Numpy array is mutable

In [28]:
a = np.array([1, 2, 3])
a[0] = 5
print(a)

[5 2 3]


In [49]:
a.flags.writeable = False

In [50]:
a[2] = 6

ValueError: assignment destination is read-only